# Patch using Path Strategic Merge: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/#patch-using-path-strategic-merge
# patchファイルでは apiVersion, kind, metadata.name を指定して、パッチを適用するリソースを特定します。
apiVersion: batch/v1
kind: CronJob
metadata:
  name: timecard-crawler
spec:
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: timecard-crawler  # crawlerを実行するサービスアカウント
          containers:
          - name: timecard-crawler
            image: 674582907715.dkr.ecr.ap-northeast-1.amazonaws.com/kintaro/prd/app:20240624.2356
            command: ["poetry", "run", "python", "crawler.py"]
            env:
            - name: DYNAMO_TABLE_NAME
              value: "kintaro-prd-users"
            - name: SECRET_NAME
              value: "/kintaro/prd/app"
            - name: APP_BUCKET
              value: kintaro-app
            - name: SQS_URL
              value: "https://sqs.ap-northeast-1.amazonaws.com/674582907715/kintaro-prd-TimecardJobQueue"
            imagePullPolicy: Always  # デプロイされるたびに常に最新のイメージを取得 (default)
          restartPolicy: OnFailure  # コンテナがエラー（非ゼロ終了ステータス）で終了した場合のみ再起動します。