# Patch using Path Strategic Merge: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/#patch-using-path-strategic-merge
# patchファイルでは apiVersion, kind, metadata.name を指定して、パッチを適用するリソースを特定します。
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-aws-credentials
spec:
  podIdentity:
    provider: aws
    # KEDAがtriggerとして利用するSQSにアクセスするためのIAM Role
    roleArn: arn:aws:iam::674582907715:role/kintaro-prd-KedaTriggerAuthRole
