# Kustomization File: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
# Kustomizeの概要と使い方: https://note.shiftinc.jp/n/nd7f17e51d592#ef1a28c4-390c-4359-9f2f-48134111fdd8
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/namespace/
#   既存の名前空間がリソースに設定されている場合は上書き、リソースに設定されていない場合は追加
namespace: kintaro-prd

# images: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/images/
# nameに一致するコンテナイメージのタグを上書き
#images:
#- name: kintaro/app
#  newName: 674582907715.dkr.ecr.ap-northeast-1.amazonaws.com/kintaro/prd/app
#  newTag: latest

# patches: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/
#   - Patch using Path Strategic Merge: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/#patch-using-path-strategic-merge
patches:
- path: crawler_service_account.patch.yaml
- path: crawler_cronjob.patch.yaml
- path: app_service_account.patch.yaml
- path: app_deployment.patch.yaml
- path: job_scaled_job.patch.yaml
- path: job_service_account.patch.yaml
- path: job_trigger_authentication.patch.yaml

# baseのkustomization.yamlが存在するディレクトリの相対パスを指定
resources:
- ../../base