version: '3.2'
services:
  main:
    hostname: main.kintaro.local
    build:
      context: ../
      dockerfile: docker/devcontainer/Dockerfile
    volumes:  # docker-compose.yml があるディレクトリからの相対パスで指定する
      - ..:/kintaro:cached
      - ~/.aws:/home/vscode/.aws:cached
      - ~/.ssh:/home/vscode/.ssh:cached
    command: sleep infinity
    networks:
      br-kintaro: {}
  localstack:
    hostname: localstack.kintaro.local
    build:
      context: ../
      dockerfile: docker/localstack/Dockerfile
    restart: unless-stopped
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      # LocalStack - init-fooks: https://docs.localstack.cloud/references/init-hooks/
      - ../docker/localstack/init:/etc/localstack/init
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      br-kintaro: {}
networks:
  br-kintaro:
    driver: bridge
    name: br-kintaro