version: '3.2'
services:
  main:
    hostname: main.kintaro.local
    build:
      context: ../
      dockerfile: docker/devcontainer/Dockerfile
    volumes:  # docker-compose.yml があるディレクトリからの相対パスで指定する
      - ..:/kintaro:cached
      - ~/.aws:/home/vscode/.aws:cached
      - ~/.ssh:/home/vscode/.ssh:cached
    command: sleep infinity
    networks:
      br-kintaro: {}

networks:
  br-kintaro:
    driver: bridge
    name: br-kintaro