---
# ネームスペース
apiVersion: v1
kind: Namespace
metadata:
  name: kintaro-default

---
# timecard-job(アプリ)を実行するサービスアカウント
apiVersion: v1
kind: ServiceAccount
metadata:
  name: timecard-job
  annotations:
    # terraformのoutputの app_role_arn に修正
    eks.amazonaws.com/role-arn: ApplicationRoleArn

---
# KEDAがSQSをポーリングするための認可情報
# TriggerAuthentication: https://keda.sh/docs/2.14/concepts/authentication/#re-use-credentials-and-delegate-auth-with-triggerauthentication
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-aws-credentials
spec:
  podIdentity:
    # AWS (IRSA Pod Identity Webhook): https://keda.sh/docs/2.14/authentication-providers/aws/
    provider: aws
    # aws provider には roleArnモード と identityOwnerモードがある
    # roleArnモードでは、keda-operatorが任意のIAM RoleをAssumeRoleしてSQSにアクセスします。
    # 指定したIAM Roleの権限のみが適用されるため、最小権限の原則に従ってアクセス権限を設定することが可能です。
    roleArn: KedaTriggerAuthRoleArn

---
# KEDAが実行するジョブの定義
# Scaling Jobs | KEDA: https://keda.sh/docs/2.14/concepts/scaling-jobs/
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: timecard-job
spec:
  pollingInterval: 30
  jobTargetRef:
    parallelism: 1
    completions: 1
    backoffLimit: 1 # 失敗時のリトライ回数
    ttlSecondsAfterFinished: 300  # ジョブの完了後に削除されるまでの秒数
    # Jobs: https://kubernetes.io/docs/concepts/workloads/controllers/job/
    template:
      spec:
        serviceAccountName: timecard-job  # jobを実行するサービスアカウント
        restartPolicy: Never
        containers:
        - name: timecard-job
          image: kintaro/app
          command: ["poetry", "run", "python", "job.py"]
          env:
          - name: SQS_URL  # ※ terraformのoutputの app_sqs_url に修正
            value: JobQueueUrl
          - name: APP_BUCKET  # ※ terraformのoutputの app_sqs_url に修正
            value: BucketName
  triggers:
  # AWS SQS Queue: Triggerhttps://keda.sh/docs/2.14/scalers/aws-sqs/
  - type: aws-sqs-queue
    metadata:
      # terraformのoutputの app_sqs_url に修正
      queueURL: JobQueueUrl
      awsRegion: ap-northeast-1
      queueLength: "1"  # 一つのpodが処理するメッセージ数
    authenticationRef:
      name: keda-trigger-auth-aws-credentials

---
# 動作確認用サンプルジョブ
# https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/job-v1/
#apiVersion: batch/v1
#kind: Job
#metadata:
#  name: sample-job
#spec:
#  ttlSecondsAfterFinished: 60  # ジョブの完了後に削除されるまでの秒数
#  backoffLimit: 1  # 失敗時のリトライ回数
#  # https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/job-v1/#JobSpec
#  template:
#    spec:
#      serviceAccountName: timecard-job
#      containers:
#      - name: sample-job
#        image: 674582907715.dkr.ecr.ap-northeast-1.amazonaws.com/kintaro/xxx/app:latest
#        command: ["aws", "s3", "ls"]
#      restartPolicy: Never  # コンテナの再起動設定。DeploymentならAlways, JobならNeverかOnFailure
