---
# timecard-job(バッチ)を実行するサービスアカウント
apiVersion: v1
kind: ServiceAccount
metadata:
  name: timecard-job
  annotations:
    # terraformのoutputの app_role_arn に修正
    eks.amazonaws.com/role-arn: ApplicationRoleArn

---
# KEDAがSQSをポーリングするための認可情報
# TriggerAuthentication: https://keda.sh/docs/2.14/concepts/authentication/#re-use-credentials-and-delegate-auth-with-triggerauthentication
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-aws-credentials
spec:
  podIdentity:
    # AWS (IRSA Pod Identity Webhook): https://keda.sh/docs/2.14/authentication-providers/aws/
    provider: aws
    # aws provider には roleArnモード と identityOwnerモードがある
    # roleArnモードでは、keda-operatorが任意のIAM RoleをAssumeRoleしてSQSにアクセスします。
    # 指定したIAM Roleの権限のみが適用されるため、最小権限の原則に従ってアクセス権限を設定することが可能です。
    roleArn: KedaTriggerAuthRoleArn

---
# KEDAが実行するジョブの定義
# Scaling Jobs | KEDA: https://keda.sh/docs/2.14/concepts/scaling-jobs/
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: timecard-job
spec:
  pollingInterval: 30
  jobTargetRef:
    parallelism: 1
    completions: 1
    backoffLimit: 1 # 失敗時のリトライ回数
    ttlSecondsAfterFinished: 300  # ジョブの完了後に削除されるまでの秒数
    # Jobs: https://kubernetes.io/docs/concepts/workloads/controllers/job/
    template:
      spec:
        serviceAccountName: timecard-job  # jobを実行するサービスアカウント
        restartPolicy: Never
        containers:
        - name: timecard-job
          image: kintaro/app
          command: ["poetry", "run", "python", "job.py"]
          env:
            - name: DYNAMO_TABLE_NAME  # ※ terraformのoutputの dynamodb_table_name に修正
              valueFrom:
                configMapKeyRef:
                  name: timecard-env
                  key: DYNAMO_TABLE_NAME
            - name: SECRET_NAME  # ※ terraformのoutputの secret_name に修正
              valueFrom:
                configMapKeyRef:
                  name: timecard-env
                  key: SECRET_NAME
            - name: APP_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: timecard-env
                  key: APP_BUCKET
            - name: SQS_URL  # ※ terraformのoutputの app_sqs_url に修正
              valueFrom:
                configMapKeyRef:
                  name: timecard-env
                  key: SQS_URL
        volumes:
          - name: env
            configMap:
              name: timecard-env
  triggers:
  # AWS SQS Queue: Triggerhttps://keda.sh/docs/2.14/scalers/aws-sqs/
  - type: aws-sqs-queue
    metadata:
      # terraformのoutputの app_sqs_url に修正
      queueURL: JobQueueUrl
      awsRegion: ap-northeast-1
      queueLength: "1"  # 一つのpodが処理するメッセージ数
    authenticationRef:
      name: keda-trigger-auth-aws-credentials
