# Kustomization File: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
# Kustomizeの概要と使い方: https://note.shiftinc.jp/n/nd7f17e51d592#ef1a28c4-390c-4359-9f2f-48134111fdd8
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# resources: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/resource/
resources:
# 全環境共通の定義が記述されたマニフェストファイルを指定
- job.yaml